### ISSUE TITLE
Unable to create release apk

### ISSUE THREAD

**Issue by darrelRayen** [sromku/build-android-jenkins#1]
Hi. I followed your [tutorial](https://www.sromku.com/blog/build-android-jenkins-types#gradle_configurations) to create a release build via Jenkins for my android application. The issue is I am getting the following error when I am trying to build release apk

`14:15:23 > com.android.ide.common.signing.KeytoolException: Failed to read key RecruiterHarver from store "/home/darrel/AndroidStudioProjects/HarverGit/android-recruiter-app/keystore-file/android.jks": Keystore was tampered with, or password was incorrect`

I am 100% sure about the credentials. But still the apk is failing to be created. But when I build i using Android Studio it works. Can you please help me on this ???

**Comment by aadilmehrajbhat** [comment]
@darrelRayen  It works fine for me I was able to generate both debug and release build successfully.
Are you placing the `debug.keystore` and `release.keystore` in `/Users/Shared/Jenkins/Home/workspace/<JenkinProjectName>/keystore/` directory?

**Comment by darrelRayen** [comment]
Thank you very much for replying ! Actually the issue was due a corrupted keystore file. It is solved now. Thank you !
